### ISSUE TITLE
Exception Value: PY_SSIZE_T_CLEAN macro must be defined for '#' formats on Python 3.10

### ISSUE THREAD

**Issue by krbanton** [ionelmc/django-uwsgi-cache#13]
Hello!

I'm having the following error using django-uwsgi-cache on Python 3.10 in conjunction with Django 4.0.6 on Ubuntu 22.04:
File "/site_package_path/lib/python3.10/site-packages/django/utils/cache.py", line 388, in get_cache_key
   headerlist = cache.get(cache_key)
File "/site_package_path/lib/python3.10/site-packages/uwsgicache.py", line 48, in get
   val = self._cache.cache_get(stringify(full_key), self._server)
Exception Type: SystemError at /file_path/favicon.png
Exception Value: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

I'm not quite sure how to fix this particular error, since it seems as though this library needs a patch to work with the 3.10 PY_SSIZE_T_CLEAN breaking change.

**Comment by ionelmc** [comment]
As you can see this library doesn't implement a c extension. This error most certainly comes from uwsgi.

**Comment by ionelmc** [comment]
Try this: https://www.google.com/search?q=uwsgi+%22PY_SSIZE_T_CLEAN+macro+must+be+defined+for+%27%23%27+formats%22

**Comment by krbanton** [comment]
Ok. Thank you so much for the prompt support! It's much appreciated!
